name: CI Pipeline

on: [push]

jobs:
  build:
    name: Build tool 
    runs-on: ubuntu-latest
    steps:
      # Clean up Docker system
      - name: Clean up Docker system
        run: |
          docker system prune --all --force
          docker volume prune --force
          docker network prune --force
    
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        # with:
        #   lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          unityVersion: 2022.3.42f1

      # # Clean up Docker system
      # - name: Clean up Docker system after test
      #   run: |
      #     docker system prune --all --force
      #     docker volume prune --force
      #     docker network prune --force

      # # Build
      # - name: Build project
      #   uses: game-ci/unity-builder@v4
      #   env:
      #     UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #     UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      #     UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      #   with:
      #     targetPlatform: Android
      #     unityVersion: 2022.3.42f1
      #     allowDirtyBuild: true

      # # Output
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: Build
      #     path: build
